version: '3.8'

services:
  app:
    build: .
    image: public_complaint_system-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=${MONGO_URL}  # This will load the value from the .env file

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
