name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Docker Compose CI"]  # Trigger when Docker Compose CI workflow finishes
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI and authenticate with EKS
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

      # Step 3: Update Kubeconfig for EKS
      - name: Update Kubeconfig for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name public_complaint_system_cluster

      # Step 4: Check if deployment.yml has changed
      - name: Check if deployment.yml has changed
        id: check_deployment
        run: |
          git fetch --prune --unshallow
          # Check if deployment.yml has changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'k8s/deployment.yml'; then
            echo "deployment.yml has changed"
            echo "needs_deploy=true" >> $GITHUB_ENV
          else
            echo "deployment.yml has not changed"
            echo "needs_deploy=false" >> $GITHUB_ENV
          fi

      # Step 5: Apply Kubernetes resources (Deployment, Service, Ingress)
      - name: Apply Kubernetes Resources (Deployment, Service, Ingress)
        if: env.needs_deploy == 'true'  # Only apply if deployment.yml has changed
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml  # Apply Service if needed
          kubectl apply -f k8s/ingress.yml  # Apply Ingress if needed

      # Step 6: Update Kubernetes Deployment with new Docker images
      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/public-complaint-system public-complaint-system=phaneendrasharma1/public_complaint_repo:public_complaint_system-app-${{ github.sha }}
          kubectl set image deployment/mongo mongo=phaneendrasharma1/public_complaint_repo:mongo-${{ github.sha }}
          kubectl rollout status deployment/public-complaint-system
          kubectl rollout status deployment/mongo
